from datetime import datetime

def generate_report(agent_output: str, output_file: str = None) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""# Sales Intelligence Report
**Generated:** {timestamp}

---

{agent_output}

---
*This report was generated by Sales Data Intelligence Agent.*
"""

    if output_file:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(report)

    return report
